joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_wheel_joint']
  right_wheel: ['right_wheel_joint']
  publish_rate: 50
  wheel_separation: 0.2206
  wheel_radius: 0.03
  base_frame_id: base_link
  cmd_vel_timeout: 0.25
  
gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 0.1
      i: 0.0
      d: 0.0
    right_wheel_joint:
      p: 0.1
      i: 0.01
      d: 0.0
    castor_wheel_joint:
      p: 0.05
      i: 0.0
      d: 0.0
