controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base_cap_joint_1
      - link_1_joint_2
      - link_2_joint_3
      - link_3_joint_4
      - link_4_joint_5
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gear_1_joint_6
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: zero_pose
  - group: hand
    pose: hand_closed