# moveit_simple_controller_manager:
#   controller_names:
#     - robot_arm_controller
#     - hand_ee_controller
#   robot_arm_controller:
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - base_cap_joint_1
#       - link_1_joint_2
#       - link_2_joint_3
#       - link_3_joint_4
#       - link_4_joint_5
#   hand_ee_controller:
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     joints:
#       - gear_1_joint_6
#       - gear_2_joint_8

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_cap_joint_1
      - link_1_joint_2
      - link_2_joint_3
      - link_3_joint_4
      - link_4_joint_5
      - gear_1_joint_6
      - gear_2_joint_8
