joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: [left_wheel_joint]
  right_wheel: [right_wheel_joint]
  wheel_separation: 0.22
  wheel_radius: 0.033
  publish_rate: 50
  cmd_vel_timeout: 0.25
  enable_odom_tf: true

gazebo_ros_control:
  pid_gains:
    left_wheel_joint: {p: 1.0, i: 0.0, d: 0.01}
    right_wheel_joint: {p: 1.0, i: 0.0, d: 0.01}

