# Arm joint trajectory controller
robot_arm_controller:
  type: "joint_trajectory_controller/JointTrajectoryController"
  joints:
    - base_cap_joint_1
    - link_1_joint_2
    - link_2_joint_3
    - link_3_joint_4
    - link_4_joint_5
  gains: # PID gains required even if not used
    base_cap_joint_1: {p: 100, d: 1, i: 1, i_clamp: 1}
    link_1_joint_2: {p: 100, d: 1, i: 1, i_clamp: 1}
    link_2_joint_3: {p: 100, d: 1, i: 1, i_clamp: 1}
    link_3_joint_4: {p: 100, d: 1, i: 1, i_clamp: 1}
    link_4_joint_5: {p: 100, d: 1, i: 1, i_clamp: 1}

# End effector joint trajectory controller
hand_ee_controller:
  type: "joint_trajectory_controller/JointTrajectoryController"
  joints:
    - gear_1_joint_6
    - gear_2_joint_8
  gains:
    gear_1_joint_6: {p: 100, d: 1, i: 1, i_clamp: 1}
    gear_2_joint_8: {p: 100, d: 1, i: 1, i_clamp: 1}

# Joint state publisher
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

